---
- name: Deploy ReadNest App
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Stop old app container
      command: docker stop cicd-demo-app
      ignore_errors: yes

    - name: Remove old app container
      command: docker rm cicd-demo-app
      ignore_errors: yes

    - name: Start new app container
      command: docker run -d --name cicd-demo-app -p 5000:5000 cicd-demo-app:latest

    - name: Start Prometheus container
      command: docker start prometheus
      ignore_errors: yes

    - name: Start Grafana container
      command: docker start grafana
      ignore_errors: yes

    - name: App status
      debug:
        msg: "ReadNest is live at localhost:5000"