---
- name: Deploy ReadNest App
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Start Flask app container
      command: docker start cicd-demo-app
      ignore_errors: yes

    - name: Start Prometheus container
      command: docker start prometheus
      ignore_errors: yes

    - name: Start Grafana container
      command: docker start grafana
      ignore_errors: yes

    - name: Verify Flask app is running
      uri:
        url: http://localhost:5000
        method: GET
        status_code: 200
      ignore_errors: yes

    - name: App status
      debug:
        msg: "ReadNest is live at localhost:5000"